### PR TITLE
proper 1.18.0 date in changes

### PR DESCRIPTION
**Pull request by karel-m**
just cosmetics

### CODE REVIEW

**Comment by sjaeckel** [comment]
dammit, again :<

**Comment by sjaeckel** [comment]
btw changes like that could go directly to develop and can be marked with '[skip ci]'

**Comment by karel-m** [comment]
What about adding something like:
```diff
--- a/makefile_include.mk
+++ b/makefile_include.mk
@@ -458,6 +458,8 @@ zipup: $(call print-help,zipup,Prepare the archives for a release) doc/crypt.pdf
        cp doc/crypt.pdf libtomcrypt-$(VERSION)/doc/crypt.pdf
        tar -c libtomcrypt-$(VERSION)/ | xz -6e -c - > crypt-$(VERSION).tar.xz
        zip -9rq crypt-$(VERSION).zip libtomcrypt-$(VERSION)
+       @echo 'fixme check'
+       -@(find libtomcrypt-$(VERSION)/ -type f | xargs grep 'FIXM[E]') && echo '############## BEWARE: the "fixme" marker found !!! ##############'
        rm -rf libtomcrypt-$(VERSION)
        gpg -b -a crypt-$(VERSION).tar.xz
        gpg -b -a crypt-$(VERSION).zip
```

**Comment by sjaeckel** [comment]
I thought the same!

**Pull request merged**
