### PR TITLE
Statically allocated key in hmac_state

### PR DESCRIPTION
**Pull request by pascal-brand38**
Signed-off-by: Pascal Brand pascal.brand@st.com

### CODE REVIEW

**Comment by tomstdenis** [comment]
The downside though is you increase the stack usage of anyone who put hmac_state on their stack.  They could malloc/free it but that was handled internally originally (which is more ideal).

If you're worried about the malloc/free cycle with the init/done you could add a done_and_reset function which done calls with a flag saying "free" meanwhile others can call it with "don't free" and then immediately jump back to "process" a new message.

**Comment by pascal-brand-st-dev** [comment]
On one hand, I agree.

But on the other hand, if you look at omac_state (and others), we have the same scheme: omac_state contains several static arrays. So the current pull-request makes the code more unified.

Indeed, we try to minimize the heap. So minimizing malloc/free is fine for us. The solution you proposed would not fit in our case I think. However, what could be ok for us is to compile one solution or another based on a new LTC_xxx definition. I can propose something that could limit the impact on the code if you're interested.

**Comment by tomstdenis** [comment]
That makes sense (to be honest I haven't look at LTC code in a really long time).  The downside to having static arrays though is that if a hash comes around with a larger block size it could cause problems requiring a LTC recompile.  Which isn't the end of the world but isn't a design goal of the project [at least originally].

Given that the other MACs used static arrays I think it's appropriate to change the hmac code over.

**Comment by sjaeckel** [comment]
> The downside though is you increase the stack usage of anyone who put `hmac_state`

TBH that was also my first concern.
But as `hmac_state` already contains two instances of `hash_state` it's not that big of a difference to have another 124 resp. 120 bytes on the stack...

> The downside to having static arrays though is that if a hash comes around with a larger block size it could cause problems requiring a LTC recompile.

Valid reason why we shouldn't do that, but as the allocation uses a Macro for its size a recompile would be required in any case.

> Which isn't the end of the world but isn't a design goal of the project [at least originally].

Well, the layout with static arrays was always there and has not been touched.
The only MAC that used dynamic allocation was HMAC...

So there would be two approaches to have the same scheme for all MAC's:

1. Apply that patch
2. Modify all other MAC's to use dynamic allocation

In regards to ABI breakage, for the case of a hash with larger block size coming around we would have to do approach 2...

**Comment by pascal-brand-st-dev** [comment]
Another implementation can be found in #68. This allows to choose, at compile time, between static and dynamic version.

**Comment by karel-m** [comment]
I am perhaps a bit late to this discussion but looking at #63 (this PR) and alternative #64 I support #63 
* consistency - as mentioned above it is consistent with other mac algs
* it is simple and clear - in fact the final code is even simpler (compared to the newly introduced set of macros in #64)
* I am afraid of future maintenance costs if we would apply #64 (and you know, we are not that good at maintenance)
* Also properly testing both new branches (static/dynamic) is an extra complexity that will consume our limited resources
* I understand that wasting the stack space is not good. But frankly speaking I do not see so many request/reports/bugs/pulls demanding lower stack usage. Once they appear, let us solve them.

**Comment by jforissier** [comment]
FYI, OP-TEE also went the "static" route (see https://github.com/OP-TEE/optee_os/commit/947ebd697b79) so I suppose https://github.com/libtom/libtomcrypt/pull/64 can be closed (at least, OP-TEE won't be pushing for it to be merged).
Thanks!

**Pull request closed without merging**
