### PR TITLE
fix base64_encode to properly add NUL termination

### PR DESCRIPTION
**Pull request by karel-m**
this one is really interesting

### CODE REVIEW

**Comment by sjaeckel** [comment]
True, very nice one!

it's somehow a nice mix of "NUL-termination" and "return actual length in length-pointer"

and I like especially the following use-case in the version before this fix...
```
p = malloc(1234);
base64_decode(foo, &bar, ...);
p = realloc(p, bar);
```

**Comment by karel-m** [comment]
The fix will probably break a lot of code.

For consistency it might be better **not** to add terminating NUL byte in all `base(16|32|64)_encode` functions.

**Comment by karel-m** [comment]
Or we can "break" for consistency `base(16|32)_encode` in the same way as `base64_encode`.

**Comment by karel-m** [comment]
I think it would be better to apply #370 instead of this PR.

**Comment by sjaeckel** [comment]
closed in favor of #371

**Pull request closed without merging**
