### PR TITLE
Fix for issue #131 (MS Visual Studio troubles)

### PR DESCRIPTION
**Pull request by grimdoomer**
Fixed the custom build step for aes.c to use the %(PreprocessorDefinitions) macro and changed $(InputFile) to "%(FullPath)" so that the project can be built from file paths that contain spaces. Added Visual Studio solution file for VS 2015.

### CODE REVIEW

**Comment by karel-m** [comment]
I would prefer not to introduce the new `libtomcrypt_VS2015*` files.

I believe that `libtomcrypt_VS2008.sln` can be easily inported & upgraded by VS2015.

We have serious troubles to keep `libtomcrypt_VS2008.*` working so why to increase maintenance cost even more.

**Comment by grimdoomer** [comment]
I removed the VS 2015 project files.

**Comment by karel-m** [comment]
I see this (MS Visual C++ 2008):
```
1>------ Build started: Project: libtomcrypt, Configuration: Debug Win32 ------
1>Performing Custom Build Step
1>cl : Command line warning D9035 : option 'GX' has been deprecated and will be removed in a future release
1>cl : Command line warning D9036 : use 'EHsc' instead of 'GX'
1>cl : Command line warning D9002 : ignoring unknown option '/MLd'
1>cl : Command line warning D9024 : unrecognized source file type '(FullPath)', object file assumed
1>LINK : fatal error LNK1181: cannot open input file '(FullPath).obj'
1>cl : Command line warning D9035 : option 'GX' has been deprecated and will be removed in a future release
1>cl : Command line warning D9036 : use 'EHsc' instead of 'GX'
1>cl : Command line warning D9002 : ignoring unknown option '/MLd'
1>cl : Command line warning D9024 : unrecognized source file type '(FullPath)', object file assumed
1>LINK : fatal error LNK1181: cannot open input file '(FullPath).obj'
1>Project : error PRJ0019: A tool returned an error code from "Performing Custom Build Step"
1>Build log was saved at "file://d:\git\libtomcrypt\Debug\BuildLog.htm"
1>libtomcrypt - 3 error(s), 8 warning(s)
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by grimdoomer** [comment]
I looked deeper into the issue and it seems that VS 2008 does not support expanding %(FullPath) even though it is used as a meta data field in the project files. 

I tried surrounding $(InputPath) with quotes to see if that would fix the issue with spaces in the file path but it still does not get expanded correctly and produces the same error.

I removed the custom build step on aes.c and was able to build successfully in VS 2008, so I'm now wondering why the custom build step is needed at all?

**Comment by karel-m** [comment]
> I removed the custom build step on aes.c and was able to build successfully in VS 2008, so I'm now wondering why the custom build step is needed at all?

AFAIK it is related to `aes_enc.o(bj)` stuff which we can perhaps ignore in MSVC builds

@sjaeckel ?

**Comment by karel-m** [comment]
Could you please:

1/ remove custom build steps for `aec|aes_enc` (I do not think that there will be so high demand for encrypt only aes in Windows land)

2/ add a define `_CRT_SECURE_NO_WARNINGS`

**Comment by karel-m** [comment]
and

3/ add also a define `LTC_NO_TEST`

**Comment by sjaeckel** [comment]
Not 100% sure though, but I think that custom build step became unnecessary in #37

**Comment by karel-m** [comment]
@grimdoomer could you please check whether the branch `fix/109-alternative-approach` fixes your troubles (it contains some changes recently merged to develop + better LTC_FAST handling which should make MSVC build smoother).

**Comment by karel-m** [comment]
closing this one as we have #168 so please move further discussion there

**Pull request closed without merging**
