### PR TITLE
renamed class -> klass

### PR DESCRIPTION
**Pull request by MilkywayPwns**
Compilation errors fixed with msvc, causes keyword issues.

### Checklist

* [x] documentation is added or updated
* [x] tests are added or updated

### CODE REVIEW

**Comment by karel-m** [comment]
What troubles do you exactly have?

The `class` works fine for me with VS2008 and VS2017.

**Comment by MilkywayPwns** [comment]
I am using VS2017 (using the latest windows SDK), this is what I get when I include tomcrypt.h:

1>\deps\libtomcrypt\src\headers\tomcrypt_pk.h(548): error C2236: unexpected token 'class'. Did you forget a ';'?
1>\deps\libtomcrypt\src\headers\tomcrypt_pk.h(548): error C2332: 'class': missing tag name
1>\deps\libtomcrypt\src\headers\tomcrypt_pk.h(548): warning C4201: nonstandard extension used: nameless struct/union
1>\deps\libtomcrypt\src\headers\tomcrypt_pk.h(548): error C2027: use of undefined type 'ltc_asn1_list_::<unnamed-tag>'

Renaming class -> asnclass fixed the issue for me.
NOTE: Previous updates and the master branch work fine.

**Comment by karel-m** [comment]
Are you including `<libtomcrypt.h>` into a C++ project? 

Just asking - although not heavily tested it should work (to some extent).

**Comment by karel-m** [comment]
I was able to reproduce with `g++`

```
In file included from src/headers/tomcrypt.h:88:0,
                 from cpp-demo.cpp:9:
src/headers/tomcrypt_pk.h:548:24: error: expected identifier before ‘;’ token
    ltc_asn1_class class;
                        ^
src/headers/tomcrypt_pk.h:548:24: error: multiple types in one declaration
src/headers/tomcrypt_pk.h:548:24: error: declaration does not declare anything [-fpermissive]
```

and with `clang++`

```
In file included from cpp-demo.cpp:9:
In file included from src/headers/tomcrypt.h:88:
src/headers/tomcrypt_pk.h:548:19: error: declaration of anonymous class must be a definition
   ltc_asn1_class class;
                  ^
src/headers/tomcrypt_pk.h:548:4: warning: declaration does not declare anything [-Wmissing-declarations]
   ltc_asn1_class class;
   ^~~~~~~~~~~~~~
```

so, yes, we should rename it

**Comment by MilkywayPwns** [comment]
Yeah, I am indeed using libtom in a C++ project.

**Comment by sjaeckel** [comment]
thx for updating the doc, can you please rename it to `klass` instead? :)

**Comment by karel-m** [comment]
👍 for `klass`

**Comment by MilkywayPwns** [comment]
Alrigthy :P

**Comment by sjaeckel** [comment]
... and please rebase on top of develop ... sorry I only realized now that there was another PR merged already ... :-)

If you plan to open another PR feel free to say in advance, then I can give you write-access to the repository.

**Comment by MilkywayPwns** [comment]
I will create a new pull request, based on latest develop.

**Comment by sjaeckel** [comment]
> I will create a new pull request, based on latest develop.

there's no need

if you don't have a remote for the original repo

```
git remote add libtom https://github.com/libtom/libtomcrypt.git
git fetch libtom
```
then
```
git checkout develop
git rebase libtom/develop
git push -f
```

**Comment by MilkywayPwns** [comment]
@sjaeckel Done, thanks for the explanation ^^

**Comment by sjaeckel** [comment]
now you did a merge somewhere in between :D

**Comment by sjaeckel** [comment]
now there are two merges in there :>

**Comment by MilkywayPwns** [comment]
I will do a hard reset to commit 249d469 and re-push the changes, that should do it, right?

**Comment by sjaeckel** [comment]
You can do a `git reset --hard 0fb3c882339b7f8a558215c32e8f74c569534082`, then force-push and that should be it.

**Comment by MilkywayPwns** [comment]
Alright, it should work now :P

**Comment by sjaeckel** [comment]
also fine :)
thx!

**Pull request merged**
