### PR TITLE
introduce LTC_CFLAGS and LTC_LDFLAGS

### PR DESCRIPTION
**Pull request by sjaeckel**

### CODE REVIEW

**Comment by karel-m** [comment]
Could you please also patch in this PR `makefile.unix` + `makefile.mingw` like this:
```
- LTC_CFLAGS  = $(CFLAGS) -Isrc/headers -Itests -DLTC_SOURCE 
+ LTC_CFLAGS  = -Isrc/headers -Itests -DLTC_SOURCE $(CFLAGS)
```

**Comment by sjaeckel** [comment]
@buggywhip can you please check if that works for you so we can merge this & create an RC2

**Comment by karel-m** [comment]
The trouble might IMO still happen when building `tests/*.o` see:
```
~/libtomcrypt$ CFLAGS="-DUSE_LTM -DLTM_DESC -I/usr/local/include" EXTRALIBS="-L/usr/local/lib -ltommath" make V=1 tests/ecc_test.o
gcc -I./src/headers/ -Wall -Wsign-compare -Wshadow -DLTC_SOURCE -Wextra -Wsystem-headers -Wbad-function-cast -Wcast-align -Wstrict-prototypes -Wpointer-arith -Wdeclaration-after-statement -W
no-type-limits -O3 -funroll-loops -fomit-frame-pointer -DGIT_VERSION=\"git-v1.18.0-rc1-20-ga949ef5\" -DUSE_LTM -DLTM_DESC -I/usr/local/include -Itests -c tests/ecc_test.c -o tests/ecc_test.o
```

The sequence `... -DUSE_LTM -DLTM_DESC -I/usr/local/include -Itests -c tests/ecc_test.c ...` is wrong as `-Itests` should be somewhere at the beginning, we cannot use `CFLAGS += -Itests`.

Possible workaroung might be to unconditionally put `-Itests` in `LTC_CFLAGS` like:
```diff
- LTC_CFLAGS += -I./src/headers/ -Wall -Wsign-compare -Wshadow -DLTC_SOURCE
+ LTC_CFLAGS += -I./src/headers/ -Itests -Wall -Wsign-compare -Wshadow -DLTC_SOURCE
```

**Comment by karel-m** [comment]
My suggestion to extend README.md:

Building
--------

If you have `libtommath` installed on your system:

    CFLAGS="-DUSE_LTM -DLTM_DESC" EXTRALIBS="-ltommath" make all

For building a shared library use:

    CFLAGS="-DUSE_LTM -DLTM_DESC" EXTRALIBS="-ltommath" make -f makefile.shared all

If you have `libtommath` in non-standard location:

    CFLAGS="-DUSE_LTM -DLTM_DESC -I/opt/devel/ltm" EXTRALIBS="/opt/devel/ltm/libtommath.a" make all

On unusual UNIX platforms, or if you do not have GNU make, have a look at `makefile.unix`.

On MS Windows try `libtomcrypt_VS2008.sln` (Visual Studio) or `makefile.mingw` or `makefile.msvc`.

**Comment by sjaeckel** [comment]
> My suggestion to extend README.md:

simply add it to README.md and open a PR :-)

if you add "[skip ci]" in a single line n in the commit message travis won't be triggered

**Comment by sjaeckel** [comment]
> CFLAGS="-DUSE_LTM -DLTM_DESC" EXTRALIBS="-ltommath" make all

btw. with this patch these two become equivalent

    CFLAGS="foo" make
    make CFLAGS="foo"

**Comment by karel-m** [comment]
> with this patch these two become equivalent

great, for some reason I like more `make CFLAGS=xyz` form

**Comment by sjaeckel** [comment]
> Possible workaroung might be to unconditionally put -Itests in LTC_CFLAGS like:

as already said before that's no possibility, I want at least the two CI builds to be clean (but with the latest commit that's also out of discussion now)

**Comment by karel-m** [comment]
According to my testing the last version of this PR should work even if you have an old libtomcrypt's headers installed on your system. I am for merging and releasing RC2.

**Pull request merged**
