### PR TITLE
Improved pkcs8 support

### PR DESCRIPTION
**Pull request by karel-m**
This is a re-created #403 which got closed and for some mysterious reasons cannot be re-opened. We should share the new ECC+pcks8 with RSA as the old `rsa_import_pkcs8` does not support password protected keys.

* [x] ecc_import_pkcs8
* [x] rsa_import_pkcs8
* [ ] documentation
* [x] further tests

### CODE REVIEW

**Comment by sjaeckel** [comment]
When factoring-out the relevant pkcs#8 parts into an own module, I'll put it in `src/pk/asn1/pkcs8`? or do you think it should go somewhere else?

**Comment by karel-m** [comment]
I am also not sure, perhaps

```
src/misc/pbes/pbes1_decrypt.c
src/misc/pbes/pbes2_pbkdf2_decrypt.c         (or just pbes2_decrypt.c)
src/pk/asn1/pkcs8/der_decode_pkcs8_flexi.c
```

**Comment by karel-m** [comment]
@sjaeckel do you have any plans with your ideas from `refactor/pr/pkcs8-improved` (in libtomcrypt_p)?

**Comment by sjaeckel** [comment]
I'm working on it ;)

**Comment by sjaeckel** [comment]
I've force-pushed `pr/pkcs8-improved` and created `pr/pkcs8-improved-original` which points to your original latest version

**Comment by sjaeckel** [comment]
so either we disable the PKCS#8 API's in the `LTC_EASY` build or we'd need the entire chain PKCS#8+PBES+PKCS#5+PKCS#12+PADDING ... what do you think?

... I just realized that all the PKCS options are enabled anyways for `LTC_EASY` ... so it'd be only the PADDING

**Comment by karel-m** [comment]
Adding `PADDING` to `LTC_EASY` is IMO ok.

**Comment by karel-m** [comment]
clang-tidy:
```
src/pk/ecc/ecc_import_pkcs8.c:29:41: error: statement should be inside braces [google-readability-braces-around-statements,-warnings-as-errors]
   if (flexi->type != LTC_ASN1_SEQUENCE)
                                        ^
                                         {
src/pk/ecc/ecc_import_pkcs8.c:33:44: error: statement should be inside braces [google-readability-braces-around-statements,-warnings-as-errors]
      if (!LTC_ASN1_IS_TYPE(cur, check->t))
                                           ^
                                            {
clang-tidy FAILED!
```

**Comment by sjaeckel** [comment]
> ```
> clang-tidy FAILED!
> ```

fixed locally, waiting for more review!?

**Comment by karel-m** [comment]
It looks good, but while testing with my perl test suit (which passed all pkcs8 EC/RSA tests) it turned out that the latest ECDSA changes broke some wycheproof tests - now I am trying to fix them.

**Comment by sjaeckel** [comment]
Okay, then I'll force-push so you can base your changes on top of that (if there are some to come) 

btw @rmw42 you're also welcome to review if you feel like it :)

**Comment by sjaeckel** [comment]
Do you probably have the time to create the missing test-vectors for pbes1 (sha1 with 3des), pbes2 (RC2 with weird key sizes) and encrypted cases for rsa?

**Comment by rmw42** [comment]
> btw @rmw42 you're also welcome to review if you feel like it :)

Cheers! Not sure I'd even know where to start - haven't had any dealings with PKCS#8 ^_^;;

**Comment by sjaeckel** [comment]
> ... haven't had any dealings with PKCS#8 ^_^;;

neither did I of your SSH stuff ;) 

...also I meant more in regards to the code or obvious bugs, not functionality

[edit] and no worries if you don't review, your contributions are already more than enough!

**Comment by karel-m** [comment]
> Do you probably have the time to create the missing test-vectors for pbes1 (sha1 with 3des), pbes2 (RC2 with weird key sizes) and encrypted cases for rsa?

I'll do it over the weekend.

**Comment by karel-m** [comment]
RSA + encrypted pkcs8 tests added

**Comment by sjaeckel** [comment]
> RSA + encrypted pkcs8 tests added

awesome, thanks :) 

also especially for the docs!

**Comment by karel-m** [comment]
I think it is ready for rebase & merge (after merging #438)

**Comment by sjaeckel** [comment]
Do we have to wait for #438 or can I also merge now?

**Comment by sjaeckel** [comment]
I just created testvectors for PBES2 RC2-40 and RC2-64 and they can't be handled... dunno yet why :( 

[rc2_keys.zip](https://github.com/libtom/libtomcrypt/files/2453033/rc2_keys.zip)

**Comment by karel-m** [comment]
Looks like we **can** load a key created like this:
```
openssl pkcs8 -topk8 -inform PEM -outform DER -passout pass:secret -in ../test.key \
-v2 rc2 -v2prf hmacWithSHA1 -out key_pkcs8_pbkdf2_sha1_rc2_cbc.der
```
But **cannot** load a key created like this:
```
openssl pkcs8 -topk8 -inform PEM -outform DER -passout pass:secret -in ../test.key \
-v2 rc2 -v2prf hmacWithSHA256 -out key_pkcs8_pbkdf2_sha256_rc2_cbc.der
```

**Comment by karel-m** [comment]
It looks link we incorrectly handle `hmacWithSHA256 ` as in `pbes_decrypt` there is `arg->type.h = sha1`

**Comment by sjaeckel** [comment]
got it! PBKDF2-params is specified in [rfc2898](https://tools.ietf.org/html/rfc2898) as follows and we didn't handle the optional keyLength...

```
   PBKDF2-params ::= SEQUENCE {
       salt CHOICE {
           specified OCTET STRING,
           otherSource AlgorithmIdentifier {{PBKDF2-SaltSources}}
       },
       iterationCount INTEGER (1..MAX),
       keyLength INTEGER (1..MAX) OPTIONAL,
       prf AlgorithmIdentifier {{PBKDF2-PRFs}} DEFAULT
       algid-hmacWithSHA1 }
```

**Pull request merged**
