### PR TITLE
Some linting

### PR DESCRIPTION
**Pull request by fperrad**

### CODE REVIEW

**Comment by sjaeckel** [comment]
Looks like we can either have clean linting or doxygen documentation ;-)

**Comment by fperrad** [comment]
Well, rebased with only the 2nd commit.

**Comment by sjaeckel** [comment]
I forgot to mention that it was okay! You can add it again! Looks like the latest changes to the doxygen config made it compatible

**Comment by sjaeckel** [comment]
Merged in c6b93ae

**Pull request closed without merging**
