### PR TITLE
Fix/411

### LINKED ISSUE #380: clang-tidy: clang-analyzer-security.insecureAPI.strcpy
The warnings are related to `src/misc/crypt/crypt_sizes.c` and `src/misc/crypt/crypt_constants`:
```
src/misc/crypt/crypt_constants.c:290:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, _crypt_constants[i].name);
            ^
src/misc/crypt/crypt_constants.c:290:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, _crypt_constants[i].name);
            ^
src/misc/crypt/crypt_constants.c:292:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, ",");
            ^
src/misc/crypt/crypt_constants.c:292:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, ",");
            ^
src/misc/crypt/crypt_constants.c:296:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, number);
            ^
src/misc/crypt/crypt_constants.c:296:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, number);
            ^
src/misc/crypt/crypt_constants.c:298:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, "\n");
            ^
src/misc/crypt/crypt_constants.c:298:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, "\n");
            ^
src/misc/crypt/crypt_sizes.c:350:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, _crypt_sizes[i].name);
            ^
src/misc/crypt/crypt_sizes.c:350:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, _crypt_sizes[i].name);
            ^
src/misc/crypt/crypt_sizes.c:352:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, ",");
            ^
src/misc/crypt/crypt_sizes.c:352:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, ",");
            ^
src/misc/crypt/crypt_sizes.c:356:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, number);
            ^
src/misc/crypt/crypt_sizes.c:356:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, number);
            ^
src/misc/crypt/crypt_sizes.c:358:13: warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119 [clang-analyzer-security.insecureAPI.strcpy]
            strcpy(ptr, "\n");
            ^
src/misc/crypt/crypt_sizes.c:358:13: note: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119
            strcpy(ptr, "\n");
            ^
```

Do we want to fix this?

### LINKED ISSUE #411: core dump
The testrun https://travis-ci.org/libtom/libtomcrypt/jobs/395246716 ended with

```
Testing version: v1.18.1-23-g11bdffc
uname=Linux travis-job-1416cab2-a867-4621-b3dd-b51836ad963a 4.4.0-101-generic #124~14.04.1-Ubuntu SMP Fri Nov 10 19:05:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
gcc=4.8
 COVERAGE (  ,  makefile V=1 COVERAGE=1)...
building...testing... COVERAGE test passed.
*** Error in `./constants': double free or corruption (!prev): 0x0000000001fcf010 ***
./coverage_more.sh: line 6:  9995 Aborted                 (core dumped) ./constants
```
probably someone should have a look at that? :)

_[Edit]:_ still persistent in https://travis-ci.org/libtom/libtomcrypt/jobs/395271891

### PR DESCRIPTION
**Pull request by sjaeckel**
This also fixes #411 and fixes #380 

... and re-factors how the strings are built up ...

dupes the fix done in #413 :)

### CODE REVIEW

**Comment by karel-m** [comment]
`char number[32], *ptr;` >> ` warning: unused variable ‘number’ [-Wunused-variable]`

**Comment by sjaeckel** [comment]
> char number[32], *ptr; >> warning: unused variable ‘number’ [-Wunused-variable]

yeah and some other sloppy mistakes also already fixed...

**Comment by karel-m** [comment]
Looks good - BTW: it also fixes #380

**Comment by sjaeckel** [comment]
> Looks good - BTW: it also fixes #380

that's why I didn't only fix the bug ;)

**Pull request merged**
