### PR TITLE
README building instructions

### PR DESCRIPTION
**Pull request by karel-m**

### CODE REVIEW

**Comment by karel-m** [comment]
A question: Why do we need both `-DUSE_LTM` and `-DLTM_DESC`?

The `USE_LTM` seems to be used just in some tests and demos.

**Comment by sjaeckel** [comment]
> A question: Why do we need both -DUSE_LTM and -DLTM_DESC?

true, strictly speaking `-DUSE_{LTM,TFM,GMP}` is only required when building `test`, 'tv_gen` and `timing`

**Comment by karel-m** [comment]
Wouldn't it simplify things a bit if we replace `USE_{LTM,TFM,GMP}` with `{LTM,TFM,GMP}_DESC` in `test`, `tv_gen` and `timing`?

Or if we add to `tomcrypt_test.h` something like:
```C
#if defined(LTM_DESC)
#define USE_LTM
#elif defined(TFM_DESC)
#define USE_TFM
#elif defined(GMP_DESC)
#define USE_GMP
#else
#error no math lib
#endif
```

**Comment by sjaeckel** [comment]
> Wouldn't it simplify things a bit if we replace USE_{LTM,TFM,GMP} with {LTM,TFM,GMP}_DESC in test, tv_gen and timing?

and then you can't build the library against ltm and tfm anymore and run the tests against tfm... I (currently) don't see a better way than the one implemented.
"You want to build the tests? Then choose a math library to run the tests with."

**Comment by sjaeckel** [comment]
@rofl0r fine like that?

**Comment by rofl0r** [comment]
LGTM! the only thing i wondered when reading the instructions was what those mentioned binaries would be...

**Comment by sjaeckel** [comment]
> the only thing i wondered when reading the instructions was what those mentioned binaries would be...

sorry, what do you mean?

**Comment by rofl0r** [comment]
no, i mean, i wondered what those binaries are and do, since the only practical thing i can think of is something like the "openssl" binary, ssh-keygen, etc.

**Comment by sjaeckel** [comment]
> those binaries are and do, since the only practical thing i can think of is something like the "openssl" binary, ssh-keygen, etc.

exactly, I especially like `hashsum` I think it's pretty unique in its supported hashes and it's install-worthy in my opinion
the others are... well ... demos :-)

**Comment by sjaeckel** [comment]
I guess we can merge this!?

**Comment by karel-m** [comment]
I guess we can merge this!?


IMO yes

**Pull request merged**
