### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by sjaeckel**
Minor cleanup&lil'feature PR

The only thing really worth a review is the newly introduced `copy_or_zeromem()`

The rest is just cosmetics.

Reviews are as always very welcome!

### CODE REVIEW

**Comment by karel-m** [comment]
Ad `copy_or_zeromem`
* I am not sure if we want it to be part of public API
* if it'll will be part of public API then the name is quite mysterious (I do not have a better name)
* if `copy_or_zeromem` is handy in CCM then it should be perhaps also used in other encauth cases

**Comment by sjaeckel** [comment]
> if copy_or_zeromem is handy in CCM then it should be perhaps also used in other encauth cases

I factored this out as I use it in my SIV PR as well, but I thought it doesn't really belong there, so I created this PR with other changes that belong to the features introduced there

> I am not sure if we want it to be part of public API

I'll make it private for now

> if it'll will be part of public API then the name is quite mysterious (I do not have a better name)

I think the name is okay'ish... probably one of the following would be better, not sure though:

1. `mem_copy_or_zero`
2. `memcpy_or_zero`
3. `copy_or_zero`
4. `copy_or_clean`

**Comment by karel-m** [comment]
If you make it private then no need to care about the name.

**Comment by sjaeckel** [comment]
> If you make it private then no need to care about the name.

well I prefer to have a proper name now so we don't have to think about it in case we want to make it public ;)

**Comment by karel-m** [comment]
IIUC we are doing: _"copy src to dest or zero dest (all that in constant time)"_ which sounds to me more like `copy_or_zero_dest` but I can live with `copy_or_zeromem` as well - I leave it up to you.

Another thing:
```diff
- coz &= 0x1;
+ coz = (coz == 0) ? 0 : 1;
```
so that unexpected/accidental `coz = 2` means zeromem (accidentally zeroing is better that copying)

**Pull request merged**
