### PR TITLE
Updated license for last master

### PR DESCRIPTION
**Pull request by radumvlad**
Since the license was updated on develop and since there was no release for some time already, it would be nice if the latest master had this new license as well.

### CODE REVIEW

**Comment by radumvlad** [comment]
Any news here :(?

**Comment by radumvlad** [comment]
Any opinion regarding this? :(

**Comment by radumvlad** [comment]
Any update?

**Comment by radumvlad** [comment]
What about having this on a separate branch, at least? @sjaeckel , @karel-m, @buggywhip

**Comment by rofl0r** [comment]
dude, pls stop whining and wait patiently for a reply. this is the 4th notification i'm getting now and so is everybody else watching this repo.

**Comment by tyzoid** [comment]
Closing for now, unless another contributor wants to take this up. Given this change is already in the develop branch, the primary branch would likely follow once a release is put together.

**Pull request closed without merging**
