### PR TITLE
Add aesgcm demo

### PR DESCRIPTION
**Pull request by sjaeckel**
This is a follow-up of #342

### CODE REVIEW

**Comment by karel-m** [comment]
This is basically fine, I only prefer that ` demos/*.c` are self-containing demos so that a libtomcrypt user can simply cut&paste&tweak the code.  What about putting all the stuff into `demos/aesgcm.c`?

**Comment by sjaeckel** [comment]
> This is basically fine, I only prefer that demos/*.c are self-containing demos so that a libtomcrypt user can simply cut&paste&tweak the code. What about putting all the stuff into demos/aesgcm.c?

as this originates in a PR which tried to introduce those as new API functions I thought it'd make sense to leave them separated.

**Comment by karel-m** [comment]
OK, I'll leave it up to you.

**Comment by sjaeckel** [comment]
I liked your points regarding the output-format and algorithm selection, so I thought it could probably be refactored at one point into a more general solution for all AEAD algorithms :)

**Comment by karel-m** [comment]
> a more general solution for all AEAD algorithms

Keep in mind that not all AEAD algs are suitable for file encryption due to max. size limit. GCM has limit approx. 2^39, ChaCha20Poly1305 has limit AFAIK 2^64 (or a little bit more), the other AEAD algorithms are IMO unusable for large file encryption.

**Comment by sjaeckel** [comment]
> Keep in mind that not all AEAD algs are suitable for file encryption due to max. size limit

algo | max AE
--- | ---
OCB3 | 2^48 blocks (2^55 bits or 4 petabytes)
CCM | 2^64 blocks
GCM | 2^39 - 256 bits
EAX | ?
ChaCha20Poly1305 | 2^64 blocks

true, you shouldn't use them for really large files... and we should think about creating a table with a summary of this, but this reminds me of #216 :)

**Pull request merged**
