### PR TITLE
RSA wycheproof tests

### PR DESCRIPTION
**Pull request by karel-m**
see #275

### CODE REVIEW

**Comment by sjaeckel** [comment]
Looks like this patch fixes the two remaining failing RSA vectors

```
diff --git a/src/ltc/pk/asn1/der/sequence/der_decode_sequence_ex.c b/src/ltc/pk/asn1/der/sequence/der_decode_sequence_ex.c
index 0d50e86..3100b86 100644
--- a/src/ltc/pk/asn1/der/sequence/der_decode_sequence_ex.c
+++ b/src/ltc/pk/asn1/der/sequence/der_decode_sequence_ex.c
@@ -326,3 +326,8 @@ int der_decode_sequence_ex(const unsigned char *in, unsigned long  inlen,
    }
-   err = CRYPT_OK;
+
+   if (inlen == 0) {
+      err = CRYPT_OK;
+   } else {
+      err = CRYPT_PK_INVALID_SIZE;
+   }
```

**Comment by karel-m** [comment]
But it seems that we somehow count on the old behaviour because with this patch ltc tests fail like this:
```store_test..........passed      0.011ms
rotate_test.........passed      0.058ms
misc_test...........passed      0.250ms
mpi_test............passed      1.383ms
cipher_hash_test....passed     59.643ms
mac_test............passed     11.625ms
modes_test..........passed      1.541ms
der_test............passed   5800.408ms
pkcs_1_test.........passed      5.248ms
pkcs_1_pss_test.....passed     26.930ms
pkcs_1_oaep_test....passed     28.231ms
pkcs_1_emsa_test....passed     37.601ms
pkcs_1_eme_test.....passed     36.417ms
rsa_test............Invalid sized parameter. (22)
tests/rsa_test.c:189:rsa_import(openssl_private_rsa, sizeof(openssl_private_rsa), &key)
```

**Comment by karel-m** [comment]
Your patch is IMO correct, we need to fix `rsa_import` and other places where we rely on the old (current) behaviour.

The trouble makers are places where we try parse only a partial part (the first few items) of ASN.1 sequence.

**Comment by sjaeckel** [comment]
yep, that boils down to:

```
diff --git a/src/pk/asn1/der/sequence/der_decode_sequence_ex.c b/src/pk/asn1/der/sequence/der_decode_sequence_ex.c
index 9addfa5..8a6755e 100644
--- a/src/pk/asn1/der/sequence/der_decode_sequence_ex.c
+++ b/src/pk/asn1/der/sequence/der_decode_sequence_ex.c
@@ -312,3 +312,8 @@ int der_decode_sequence_ex(const unsigned char *in, unsigned long  inlen,
    }
-   err = CRYPT_OK;
+
+   if (inlen == 0) {
+      err = CRYPT_OK;
+   } else {
+      err = CRYPT_PK_INVALID_SIZE;
+   }
 
diff --git a/src/pk/dh/dh_import.c b/src/pk/dh/dh_import.c
index 66778eb..c86f2b5 100644
--- a/src/pk/dh/dh_import.c
+++ b/src/pk/dh/dh_import.c
@@ -39,3 +39,3 @@ int dh_import(const unsigned char *in, unsigned long inlen, dh_key *key)
                                    LTC_ASN1_EOL, 0UL, NULL);
-   if (err != CRYPT_OK) {
+   if (err != CRYPT_OK && err != CRYPT_PK_INVALID_SIZE) {
       goto error;
diff --git a/src/pk/dsa/dsa_decrypt_key.c b/src/pk/dsa/dsa_decrypt_key.c
index bee276a..806ef3e 100644
--- a/src/pk/dsa/dsa_decrypt_key.c
+++ b/src/pk/dsa/dsa_decrypt_key.c
@@ -48,4 +48,4 @@ int dsa_decrypt_key(const unsigned char *in,  unsigned long  inlen,
    LTC_SET_ASN1(decode, 0, LTC_ASN1_OBJECT_IDENTIFIER, hashOID, sizeof(hashOID)/sizeof(hashOID[0]));
-
-   if ((err = der_decode_sequence(in, inlen, decode, 1)) != CRYPT_OK) {
+   err = der_decode_sequence(in, inlen, decode, 1);
+   if (err != CRYPT_OK && err != CRYPT_PK_INVALID_SIZE) {
       return err;
diff --git a/src/pk/dsa/dsa_import.c b/src/pk/dsa/dsa_import.c
index d71cdd5..5db6963 100644
--- a/src/pk/dsa/dsa_import.c
+++ b/src/pk/dsa/dsa_import.c
@@ -41,5 +41,6 @@ int dsa_import(const unsigned char *in, unsigned long inlen, dsa_key *key)
    /* try to match the old libtomcrypt format */
-   if ((err = der_decode_sequence_multi(in, inlen,
-                                  LTC_ASN1_BIT_STRING, 1UL, flags,
-                                  LTC_ASN1_EOL, 0UL, NULL)) == CRYPT_OK) {
+   err = der_decode_sequence_multi(in, inlen, LTC_ASN1_BIT_STRING, 1UL, flags,
+                                              LTC_ASN1_EOL,        0UL, NULL);
+
+   if (err == CRYPT_OK || err == CRYPT_PK_INVALID_SIZE) {
        /* private key */
diff --git a/src/pk/ecc/ecc_decrypt_key.c b/src/pk/ecc/ecc_decrypt_key.c
index e0d3fd3..4a16de9 100644
--- a/src/pk/ecc/ecc_decrypt_key.c
+++ b/src/pk/ecc/ecc_decrypt_key.c
@@ -54,4 +54,4 @@ int ecc_decrypt_key(const unsigned char *in,  unsigned long  inlen,
    LTC_SET_ASN1(decode, 0, LTC_ASN1_OBJECT_IDENTIFIER, hashOID, sizeof(hashOID)/sizeof(hashOID[0]));
-
-   if ((err = der_decode_sequence(in, inlen, decode, 1)) != CRYPT_OK) {
+   err = der_decode_sequence(in, inlen, decode, 1);
+   if (err != CRYPT_OK && err != CRYPT_PK_INVALID_SIZE) {
       return err;
diff --git a/src/pk/ecc/ecc_import.c b/src/pk/ecc/ecc_import.c
index 7c0afed..034c9bd 100644
--- a/src/pk/ecc/ecc_import.c
+++ b/src/pk/ecc/ecc_import.c
@@ -107,5 +107,5 @@ int ecc_import_ex(const unsigned char *in, unsigned long inlen, ecc_key *key, co
    /* find out what type of key it is */
-   if ((err = der_decode_sequence_multi(in, inlen,
-                                  LTC_ASN1_BIT_STRING, 1UL, flags,
-                                  LTC_ASN1_EOL,        0UL, NULL)) != CRYPT_OK) {
+   err = der_decode_sequence_multi(in, inlen, LTC_ASN1_BIT_STRING, 1UL, flags,
+                                              LTC_ASN1_EOL,        0UL, NULL);
+   if (err != CRYPT_OK && err != CRYPT_PK_INVALID_SIZE) {
       goto done;
diff --git a/src/pk/rsa/rsa_import.c b/src/pk/rsa/rsa_import.c
index a6be18d..fbae39b 100644
--- a/src/pk/rsa/rsa_import.c
+++ b/src/pk/rsa/rsa_import.c
@@ -68,5 +68,6 @@ int rsa_import(const unsigned char *in, unsigned long inlen, rsa_key *key)
    /* not SSL public key, try to match against PKCS #1 standards */
-   if ((err = der_decode_sequence_multi(in, inlen,
-                                  LTC_ASN1_INTEGER, 1UL, key->N,
-                                  LTC_ASN1_EOL,     0UL, NULL)) != CRYPT_OK) {
+   err = der_decode_sequence_multi(in, inlen, LTC_ASN1_INTEGER, 1UL, key->N,
+                                              LTC_ASN1_EOL,     0UL, NULL);
+
+   if (err != CRYPT_OK && err != CRYPT_PK_INVALID_SIZE) {
       goto LBL_ERR;
```

**Comment by karel-m** [comment]
Travis-CI is green, merge?

**Pull request merged**
