### PR TITLE
fix for #90 ltc_ecc_mul2add.c integer sign issue

### PR DESCRIPTION
**Pull request by karel-m**

### CODE REVIEW

**Comment by karel-m** [comment]
Not good :(
```
src/pk/ecc/ltc_ecc_mul2add.c: In function ‘ltc_ecc_mul2add’:
src/pk/ecc/ltc_ecc_mul2add.c:141:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

**Comment by sjaeckel** [comment]
how about the solution in abc54df?
if that's okay with the HP compiler please reset your `miko-ltc_ecc_mul2add-integer-sign-issue` branch to the commit and force-push the branch to your fork

Off-topic (for the future): you have push access to this repo. can you just push your issue branches to this repository instead of your fork and create PR's based on that, then we can easily rebase and fixup branches without the procedure required above :-) thanks

**Comment by karel-m** [comment]
your fix seems to be ok

**Comment by karel-m** [comment]
I have rebased this fix to the current develop. I am not sure if there is anything on my side here.

Considering nearly zero impact I would prefer not wait till 2.0 milestone with this PR.

**Comment by sjaeckel** [comment]
Looks also fine to me.

Btw. the milestones work the other way around ;-) milestone 2.0 won't be reached without this PR being merged

**Comment by karel-m** [comment]
OK, I'll merge it to develop

**Comment by karel-m** [comment]
merged as 979e9a9d1542d2e59638889eeca52357eeac6c6d (I used command line but probably in an unusual way as the github still considers this PR as unmerged)

**Comment by sjaeckel** [comment]
> merged as 979e9a9 (I used command line but probably in an unusual way as the github still considers this PR as unmerged)

yeah github won't close issues without you mentioning it in a commit message that goes to develop.

for the next time, please rebase and then merge with `--no-ff` (as said before...)

**Pull request closed without merging**
