### PR TITLE
Improve curve25519

### PR DESCRIPTION
**Pull request by sjaeckel**
Follow-up of #364 

* [x] documentation is added or updated
* [x] tests are added or updated

### CODE REVIEW

**Comment by karel-m** [comment]
```
src/pk/ec25519/tweetnacl.c:42:5: warning: no previous prototype for ‘crypto_verify_32’ [-Wmissing-prototypes]
 int crypto_verify_32(const u8 *x,const u8 *y)
     ^~~~~~~~~~~~~~~~
```

**Comment by sjaeckel** [comment]
This function is defined above in the same file ... would it help to make it static?

**Comment by karel-m** [comment]
yes `static` helps:
```
static int crypto_verify_32(const u8 *x,const u8 *y)
```

**Comment by sjaeckel** [comment]
:+1:

**Comment by karel-m** [comment]
Do we plan to add an option to load a private key via `x25519_import` and/or `ed25519_import`?

**Comment by karel-m** [comment]
Some warnings from `clang-tidy`

```
src/headers/tomcrypt_private.h:305:5: error: function 'crypto_sign' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name,-warnings-as-errors]
int crypto_sign(
    ^
src/pk/ec25519/tweetnacl.c:385:5: note: the definition seen here
int crypto_sign(u8 *sm,u64 *smlen,const u8 *m,u64 n,const u8 *sk,const u8 *pk)
    ^
src/headers/tomcrypt_private.h:305:5: note: differing parameters are named here: ('mlen'), in definition: ('n')
int crypto_sign(
    ^
src/headers/tomcrypt_private.h:309:5: error: function 'crypto_sign_open' has a definition with different parameter names [readability-inconsistent-declaration-parameter-name,-warnings-as-errors]
int crypto_sign_open(
    ^
src/pk/ec25519/tweetnacl.c:453:5: note: the definition seen here
int crypto_sign_open(int *stat, u8 *m,u64 *mlen,const u8 *sm,u64 n,const u8 *pk)
    ^
src/headers/tomcrypt_private.h:309:5: note: differing parameters are named here: ('smlen'), in definition: ('n')
int crypto_sign_open(
    ^
src/pk/ed25519/ed25519_import.c:38:6: error: do not use 'else' after 'return' [readability-else-after-return,-warnings-as-errors]
   } else {
     ^~~~~~
src/pk/x25519/x25519_import.c:48:6: error: do not use 'else' after 'return' [readability-else-after-return,-warnings-as-errors]
   } else {
     ^~~~~~
```

**Comment by karel-m** [comment]
We should perhaps choose some other prefix than `crypto_` for the following private functions:

```
crypto_sign
crypto_sign_open
crypto_sign_keypair
crypto_sk_to_pk
crypto_scalarmult
crypto_scalarmult_base
```

Like `crypto25519_` or  `ec25519_` or something that indicates relation to Curve25519.

**Comment by karel-m** [comment]
> Do we plan to add an option to load a private key via `x25519_import` and/or `ed25519_import`?

If I understand correctly to import a private key I have to call:
```
err = ed25519_set_key(privkey_ptr, 32, NULL, 0, &key) ;
```
right?

**Comment by sjaeckel** [comment]
Yep
Either like that or via the pkcs#8 import

**Comment by karel-m** [comment]
OK, we can fix the final key import/export/conversion interface later. I think changes from this PR should go to `develop`.

**Review by karel-m — APPROVED** [review]

**Comment by sjaeckel** [comment]
> we can fix the final key import/export/conversion interface later

any proposals on what should be changed of the current API?

**Comment by karel-m** [comment]
I was thinking about a set of import related functions like:
* `ed25519_import_pkcs8`
* `ed25519_import_x509`
* `ed25519_import_openssl` (= current `ed25519_import` + `PK_STD`)
* `ed25519_import_raw` (= current `ed25519_set_key`)

But I have to think it over.

**Comment by karel-m** [comment]
And perhaps `ed25519_export` should allow to export (convert) keys in format acceptable by `x25519_import` e.g. via a special flag `PK_PUBLIC | PK_X25519` or `PK_PRIVATE | PK_X25519`. 

Ideally in a way interoperable with https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519

**Comment by sjaeckel** [comment]
> * `ed25519_import_pkcs8`
> 
> * `ed25519_import_x509`

they're already there!?

> * `ed25519_import_openssl` (= current `ed25519_import` + `PK_STD`)
> 
> * `ed25519_import_raw` (= current `ed25519_set_key`)

if you think it's really worth it, sure...

I had the raw import functionality initially in  `*25519_import()` but then I realized that it's ambiguous as you don't know if it's a private or public key, so I removed that again in favor of `*25519_set_key`

> And perhaps `ed25519_export` should allow to export (convert) keys in format acceptable by `x25519_import` e.g. via a special flag `PK_PUBLIC | PK_X25519` or `PK_PRIVATE | PK_X25519`.

fine by me

how about `ed25519_convert_to_x25519(const *edkey, *xkey)`?

**Pull request merged**
