### PR TITLE
Improving MS Windows builds (msvc)

### PR DESCRIPTION
**Pull request by karel-m**
I have cleaned the MSVC builds in this PR.

Important changes:

1/ now we only support visual studio 2008 (and higher)

2/ `libtomcrypt_VS2008.vcproj` now supports both 32/64 bit build targets

3/ project files for VS2005 and VC6 were deleted (they were not working properly anyway)

4/ I have also slightly polished makefiles used on MS Windows

5/ couple of fixes to silence some MSVC compiler warnings (mostly cosmetics)

@grimdoomer can you please try to load `libtomcrypt_VS2008.vcproj` from this branch to your visual studio?

This PR supersedes #131 and #165

### CODE REVIEW

**Comment by grimdoomer** [comment]
@karel-m  Sure, on vacation at the moment, give me a few days and I will get back to you.

**Comment by grimdoomer** [comment]
@karel-m builds successfully on windows from a file path containing spaces.

**Comment by karel-m** [comment]
thanks @grimdoomer 

Rebased on current develop, I'll wait for travis-ci and merge it.

**Comment by karel-m** [comment]
travis-ci ignoring this branch, so simply merging

**Pull request merged**
