### PR TITLE
Correct SHA3 block sizes

### PR DESCRIPTION
**Pull request by karel-m**
### Checklist

* [x] tests are added or updated

### CODE REVIEW

**Comment by sjaeckel** [comment]
As this PR would lead (again) to a bump of the major ABI version I thought about investing some time to implement a work-around or at least catch the corner cases so the ABI version could be kept the same.
As I'm not sure if that's worth the effort, I thought probably one of you guys @rofl0r @stapelberg @sebastianas or someone else who reads this can give their opinion resp. technical reasoning which way we should go...
Thanks in advance!

**Comment by stapelberg** [comment]
As per https://codesearch.debian.net/search?q=sha3_%5B0-9%5D%2B_desc&perpkg=1, no software in Debian seems to use sha3_[0-9]+_desc, so this should be an easy transition.

**Comment by karel-m** [comment]
Looking at my own code I am in doubts whether increasing MAXBLOCKSIZE is really necessary.

**Comment by sjaeckel** [comment]
> Looking at my own code I am in doubts whether increasing MAXBLOCKSIZE is really necessary.
> View changes

the ABI bump is necessary because of the changed size of `hmac_state` (and all the other typedefs which contain `MAXBLOCKSIZE`) therefore your hack unfortunately doesn't really help...



> As per https://codesearch.debian.net/search?q=sha3_%5B0-9%5D%2B_desc&perpkg=1, no software in Debian seems to use sha3_[0-9]+_desc, so this should be an easy transition.

thanks for the info!

**Pull request merged**
