### PR TITLE
Third general clean-up

### PR DESCRIPTION
**Pull request by sjaeckel**
* fix potential timing attacks in rsa, eax, ocb and ocb3
* use `compare_testvector()` in all the algorithm tests
* use `_function()` pattern for (most of the) static functions
* improve `./test`

### CODE REVIEW

**Comment by karel-m** [comment]
Could you please introduce in this cleanup round XMEMMOVE?

```C
#ifndef XMEMMOVE
#define XMEMMOVE memmove
#endif 
```

and

```diff
--- a/helper.pl
+++ b/helper.pl
@@ -51,6 +51,7 @@ sub check_source {
       push @{$troubles->{unwanted_memset}},  $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bmemset\s*\(/;
       push @{$troubles->{unwanted_memcpy}},  $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bmemcpy\s*\(/;
       push @{$troubles->{unwanted_memcmp}},  $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bmemcmp\s*\(/;
+      push @{$troubles->{unwanted_memmove}}, $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bmemmove\s*\(/;
       push @{$troubles->{unwanted_strcmp}},  $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bstrcmp\s*\(/;
       push @{$troubles->{unwanted_clock}},   $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bclock\s*\(/;
       push @{$troubles->{unwanted_qsort}},   $lineno if $file =~ /^src\/.*\.c$/ && $l =~ /\bqsort\s*\(/;
```

**Comment by sjaeckel** [comment]
> Could you please introduce in this cleanup round XMEMMOVE?

sure, even if there's no invocation (yet ;-) )

**Comment by karel-m** [comment]
Another minor thing that needs to be cleaned up. 

During `./testme.sh "makefile -j8" "-Wall -Wextra -Werror -DUSE_LTM -DLTM_DESC -I../libtommath" ../libtommath/libtommath.a`

I see:
```
NOTEST (Build Only, -DLTC_NO_TEST, makefile -j8)...
building...build NOTEST failed see gcc_2.txt for more information
src/modes/xts/xts_test.c:13:12: error: ‘_xts_test_accel_xts_encrypt’ defined but not used [-Werror=unused-function]
 static int _xts_test_accel_xts_encrypt(const unsigned char *pt, unsigned char *ct, unsigned long blocks,
            ^
src/modes/xts/xts_test.c:40:12: error: ‘_xts_test_accel_xts_decrypt’ defined but not used [-Werror=unused-function]
 static int _xts_test_accel_xts_decrypt(const unsigned char *ct, unsigned char *pt, unsigned long blocks,
            ^
cc1: all warnings being treated as errors
```

**Comment by karel-m** [comment]
1/ Ad makefile.mingw + makefile.msvc:

I am not sure whether DESTDIR concept make sense for MS Windows paths. For example: `make -f makefile.mingw DESTDIR=c:\builddir\ PREFIX=c:\installdir` means that `"$(DESTDIR)$(PREFIX)\bin"` will expand to `"c:\builddir\c:\installdir\bin"` which is obviously invalid. I propose reverting `also use DESTDIR in makefile.m{ingw,svc}`.

2/ Ad static function names: you have excluded `src/ciphers`, `src/hashes` and `src/stream/sober128` - do you plan to fix those later?

**Comment by sjaeckel** [comment]
> 1/ Ad makefile.mingw + makefile.msvc:
> 
> I am not sure whether DESTDIR concept make sense for MS Windows paths. For example: `make -f makefile.mingw DESTDIR=c:\builddir\ PREFIX=c:\installdir` means that `"$(DESTDIR)$(PREFIX)\bin"` will expand to `"c:\builddir\c:\installdir\bin"` which is obviously invalid. I propose reverting `also use DESTDIR in makefile.m{ingw,svc}`.

right it's windows...

> 2/ Ad static function names: you have excluded `src/ciphers`, `src/hashes` and `src/stream/sober128` - do you plan to fix those later?

not sure yet (when and what) :smile: volunteers are always welcome ;-)

**Pull request merged**
