### PR TITLE
implement DER recursion limit

### PR DESCRIPTION
**Pull request by sjaeckel**

### CODE REVIEW

**Comment by buggywhip** [comment]
Looks good.  I like the default limit (30) being customizable in tomcrypt_custom.h.

**Comment by karel-m** [comment]
Have you considered:
```C
int der_decode_custom_type_ex(const unsigned char *in, unsigned long inlen,
                                     ltc_asn1_list *root,
                                     ltc_asn1_list *list, unsigned long outlen,
                                     unsigned int max_depth,
                                     unsigned int flags)
```
?

**Comment by sjaeckel** [comment]
can you please give your opinion on my previous [comment](https://github.com/libtom/libtomcrypt/pull/373#issuecomment-378265297)?

> Have you considered:
> 
> int der_decode_custom_type_ex(const unsigned char *in, unsigned long inlen,
>                                      ltc_asn1_list *root,
>                                      ltc_asn1_list *list, unsigned long outlen,
>                                      unsigned int max_depth,
>                                      unsigned int flags)
> ?

I thought about it, but I think then we could also do it like:

```
diff --git a/src/headers/tomcrypt_pk.h b/src/headers/tomcrypt_pk.h
index f312acd..3b1bc58 100644
--- a/src/headers/tomcrypt_pk.h
+++ b/src/headers/tomcrypt_pk.h
@@ -637,4 +637,4 @@ int der_decode_sequence_ex(const unsigned char *in, unsigned long  inlen,
 
-#define der_decode_sequence(in, inlen, list, outlen) der_decode_sequence_ex(in, inlen, list, outlen, LTC_DER_SEQ_SEQUENCE | LTC_DER_SEQ_RELAXED)
-#define der_decode_sequence_strict(in, inlen, list, outlen) der_decode_sequence_ex(in, inlen, list, outlen, LTC_DER_SEQ_SEQUENCE | LTC_DER_SEQ_STRICT)
+#define der_decode_sequence(in, inlen, list, outlen) der_decode_sequence_ex(in, inlen, list, outlen, ((LTC_DER_MAX_RECURSION << 8) & LTC_DER_SEQ_DEPTH) | LTC_DER_SEQ_SEQUENCE | LTC_DER_SEQ_RELAXED)
+#define der_decode_sequence_strict(in, inlen, list, outlen) der_decode_sequence_ex(in, inlen, list, outlen, ((LTC_DER_MAX_RECURSION << 8) & LTC_DER_SEQ_DEPTH) | LTC_DER_SEQ_SEQUENCE | LTC_DER_SEQ_STRICT)
 
@@ -682,3 +682,3 @@ extern const unsigned long der_asn1_type_to_identifier_map_sz;
 /* SET */
-#define der_decode_set(in, inlen, list, outlen) der_decode_sequence_ex(in, inlen, list, outlen, LTC_DER_SEQ_SET)
+#define der_decode_set(in, inlen, list, outlen) der_decode_sequence_ex(in, inlen, list, outlen, ((LTC_DER_MAX_RECURSION << 8) & LTC_DER_SEQ_DEPTH) |LTC_DER_SEQ_SET)
 #define der_length_set der_length_sequence
diff --git a/src/pk/asn1/der/custom_type/der_decode_custom_type.c b/src/pk/asn1/der/custom_type/der_decode_custom_type.c
index ebf180f..c7cf7f6 100644
--- a/src/pk/asn1/der/custom_type/der_decode_custom_type.c
+++ b/src/pk/asn1/der/custom_type/der_decode_custom_type.c
@@ -29,3 +29,3 @@ int der_decode_custom_type(const unsigned char *in, unsigned long  inlen,
    LTC_ARGCHK(root != NULL);
-   return der_decode_custom_type_ex(in, inlen, root, NULL, 0, LTC_DER_SEQ_ORDERED | LTC_DER_SEQ_RELAXED);
+   return der_decode_custom_type_ex(in, inlen, root, NULL, 0, ((LTC_DER_MAX_RECURSION << 8) & LTC_DER_SEQ_DEPTH) | LTC_DER_SEQ_ORDERED | LTC_DER_SEQ_RELAXED);
 }
@@ -143,3 +143,3 @@ int der_decode_custom_type_ex(const unsigned char *in,   unsigned long  inlen,
    depth = (flags & LTC_DER_SEQ_DEPTH) >> 8;
-   if (depth > LTC_DER_MAX_RECURSION) {
+   if (depth == 0) {
       err = CRYPT_PK_ASN1_ERROR;
@@ -147,3 +147,3 @@ int der_decode_custom_type_ex(const unsigned char *in,   unsigned long  inlen,
    }
-   depth++;
+   depth--;
    flags &= ~LTC_DER_SEQ_DEPTH;
```

so the caller has to pass-in the max-depth on usage of `der_decode_custom_type_ex()` resp. `der_decode_sequence_ex()` (which simply forwards `flags`)

**Comment by karel-m** [comment]
> I'm not sure if this should only be applied to `der_decode_sequence_flexi()` as the parameters of `der_decode_sequence()` are constructed by a developer and ...

I would only handle max depth check in `der_decode_sequence_flexi` where it is clearly a must.

**Pull request merged**
