### PR TITLE
Add SM4 block cipher

### PR DESCRIPTION
**Pull request by ChaoWeiAtGit**
SM4 (formerly SMS4)[1] is a block cipher used in the Chinese
National Standard for Wireless LAN WAPI (Wired Authentication
and Privacy Infrastructure).
--from wikipedia

### Checklist

* [ ] documentation is added or updated
* [x] tests are added or updated

### CODE REVIEW

**Comment by karel-m** [comment]
Just for record: standardisation of SM4 seems to got stuck https://tools.ietf.org/html/draft-ribose-cfrg-sm4-10

**Comment by hustliyilin** [comment]
> Just for record: standardisation of SM4 seems to got stuck https://tools.ietf.org/html/draft-ribose-cfrg-sm4-10

@karel-m  `SM4` has become an ISO/IEC standard in 2021, see https://www.iso.org/standard/81564.html for details. 

Besides, `linux kernel` and `openssl` also support `SM4`, so maybe this pr is suitable for `libtom/libtomcrypt`

**Comment by levitte** [comment]
This PR needs a bit of love.  I'm willing to fork it and have it catch up, unless @ChaoWeiAtGit is going to.

**Comment by levitte** [comment]
... considering that @ChaoWeiAtGit hasn't been github active for a long time, a takeover seems the way forward.

**Comment by levitte** [comment]
Closing this, 'cause rebooted in #657

**Pull request closed without merging**
